name: hajj_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  http: ^1.3.0
  intl: ^0.19.0
  flutter_spinkit: ^5.2.0
  shared_preferences: ^2.2.0
  flutter_localizations:
    sdk: flutter
  youtube_player_flutter: ^9.1.1
  video_player: ^2.9.3
  camera: ^0.10.5+2
  sqflite: ^2.0.0
  path: ^1.8.0
  sqflite_common_ffi: ^2.3.0
  sqlite3_flutter_libs: ^0.5.5
  image_gallery_saver: ^2.0.3
  path_provider: ^2.0.15
  geolocator: ^14.0.0
  video_thumbnail: ^0.5.3
  webview_flutter: ^4.4.2
  audioplayers: ^6.4.0
  ffi: ^2.0.1
  image: ^4.1.3
  google_mlkit_object_detection: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/makkah_bg.jpg
    - assets/google_logo.png
    - assets/apple_logo.png
    - assets/drone_image.png
    - assets/flight_logs.png
    - assets/drone_status.png
    - assets/media_library.png
    - assets/control_center.png
    - assets/drone_icon.png
    - assets/battery_graph.png
    - assets/map_image.png
    - assets/makka_alerts.png
    - assets/crowd_graph.png
    - assets/crowd_status_graph.png
    - assets/live_feed.png
    - assets/flight_path.png
    - assets/image1.jpg
    - assets/image2.jpg
    - assets/image3.jpg
    - assets/video1_thumbnail1.jpg
    - assets/video2_thumbnail.2.jpg
    - assets/video3_thumbnail3.jpg
    - assets/sunny.jpg
    - assets/night.jpg
    - assets/cloudy.jpg
    - assets/default.jpg
    - assets/cloudy_night.jpg
    - assets/night_clear.jpg
    - assets/sunrise.png
    - assets/day_cloudy.png
    - assets/night_cloudy.png
    - assets/video1.MP4
    - assets/video2.MP4
    - assets/video3.MP4
    - assets/bak.png
    - assets/ddrone_status.jpg
    - assets/med.png
    - assets/labels.txt
    - assets/cclod.png
    - assets/day.jpg
    - assets/night.mov
    - assets/morn.mov
    - assets/morn.jpg
    - assets/night.png
    - assets/c1.png
    - assets/c2.png
    - assets/c3.png
    - assets/c4.png
    - assets/c5.png
    - assets/c6.png
    - assets/c7.png
    - assets/c8.png
    - assets/c9.png
    - assets/c10.png
    - assets/c11.png
    - assets/c12.png
    - assets/c13.png
    - assets/c14.png
    - assets/c15.png
    - assets/c16.png
    - assets/c17.png
    - assets/c18.png
    - assets/c19.png
    - assets/c20.png